"""Applies native settings to the platform projects generated by `flutter create`.

Run from the repo root after `flutter create`:  python3 tool/patch_platforms.py
Safe to run twice.
"""
import re
import sys
from pathlib import Path


def patch_android():
    f = Path('android/app/build.gradle.kts')
    s = f.read_text()
    # flutter_local_notifications needs Java 17, core library desugaring and minSdk 24.
    s = s.replace('VERSION_11', 'VERSION_17').replace('JVM_11', 'JVM_17')
    if 'isCoreLibraryDesugaringEnabled' not in s:
        s, n = re.subn(r'compileOptions\s*\{', 'compileOptions {\n        isCoreLibraryDesugaringEnabled = true', s, count=1)
        if n == 0:
            sys.exit('android: compileOptions block not found')
    s = re.sub(r'minSdk\s*=\s*flutter\.minSdkVersion', 'minSdk = maxOf(24, flutter.minSdkVersion)', s)
    if 'desugar_jdk_libs' not in s:
        s += '\ndependencies {\n    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")\n}\n'
    f.write_text(s)
    print('--- android/app/build.gradle.kts ---\n' + s)


def patch_ios():
    f = Path('ios/Runner/AppDelegate.swift')
    s = f.read_text()
    if 'UNUserNotificationCenter' not in s:
        if 'import UserNotifications' not in s:
            s = s.replace('import UIKit', 'import UIKit\nimport UserNotifications', 1)
        # Lets notification taps and foreground notifications reach the plugin.
        hook = 'return super.application(application, didFinishLaunchingWithOptions: launchOptions)'
        if hook not in s:
            sys.exit('ios: didFinishLaunching return not found')
        s = s.replace(
            hook,
            'UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate\n    ' + hook,
            1,
        )
    f.write_text(s)
    print('--- ios/Runner/AppDelegate.swift ---\n' + s)


if __name__ == '__main__':
    targets = sys.argv[1:] or ['android', 'ios']
    if 'android' in targets:
        patch_android()
    if 'ios' in targets:
        patch_ios()
